language: go

go:
  - 1.7.x

services:
  - docker

matrix:
  fast_finish: true

before_install:
  - make init

script:
  - make stylecheck
  - make lint
  - make test
  - make build-all
  - make test-integration
  - make package-init
  - make package
  - make docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make docker-push;
    fi
