[openstack]
# OpenStack Keystone endpoint
auth_url="http://172.19.4.64:5000/v3"
# User with admin role in order to call 'openstack server list --all-projects'
username="platform-visibility"
password="123"
project_name="service"
region="RegionOne"
domain_name="default"
endpoint_type="internal"

[visualization_api]
endpoint="http://localhost:9080/v1"

[grafana]
endpoint="http://localhost:3000/"
auth_header="X-Webauth-User"

[http_endpoint]
# port visualization-api is listening on
port = 9081

[cookies]
# must be 32 or 64 bytes long (using ASCII character here as 1 byte)
secret="eiw3oothee0ohGucieB0Gaequoh1rahfoh5phoob5ail7thowaiM2aej2iej8eeg"
# cookies max age in seconds 172800 = 48h
max_age=172800

[log]
path = "auth_proxy.log"
level = "debug"

#log detailed request dump
request_logging = "false"
